kind: Endpoints
apiVersion: v1
metadata:
  name: keycloak-external
subsets:
  - addresses:
      - ip: 115.239.210.27
    ports:
      - port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-external
spec:
  ports:
    - port: 30888
      targetPort: 80
  externalIPs:
    - 115.239.210.27
